### ISSUE TITLE
how to document eventDate if only limited information is available

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#19]
[migrate from meeting notes 2022-06-16]

If eventDate is not available at all:
- flag from TDWG BDQ: DATE_NULL

If exact eventDate unknown, but range is known:
- Recommend: Provide a range in ISO8601 format in eventDate if possible

In case we have an event with day and month provided but not the year, how should we proceed?
- Missing year because year was not relevant - they were studying seasons
- eventDate: --06-16 is valid according to ISO 8601, populate month, day but leave year empty, mention in eventRemarks why year is missing.
- If the year range is certain, provide a range of years in eventDate (YYYY/YYYY-MM-DD), mention that in eventRemarks

**Comment by geo-sar** [comment]
@pieterprovoost could you confirm that? I recall you suggested using only month and day terms in this case.
And if so, in case we have year and month (eg August 1843) would 1843-08-- be used as eventDate or should the year and month be placed separately as in the 1st example?
Also, if we don't have any date at all. but the dataset was published in 1843, is it safe to use:
"../1843"?  Meaning that we don't know the dataset's date but it wouldn't be later than 1843 since it had been published by then.

Taken from the ISO 8601 manual "Date and time — Representations for information interchange", chapter "Unknown or open start or end time intervals"
EXAMPLE 6 '../1985', implicit form, '../1985Y', explicit form: the time interval with an open start and ending at year 1985, with year precision.

**Comment by pieterprovoost** [comment]
These are fine:

```
1843-08
1843
1800/1843
```

I suggested using `month` and `day` for missing years because the parser currently cannot handle exotic variants like `--06-16`. The same goes for patterns like `../1985`.

**Comment by geo-sar** [comment]
ok! :)
For the last one, I guess it is fine, since Forbes (the author and Identifier) was born in 1815 :p

**Comment by ymgan** [comment]
solution provided
